{
 "title": "VPA Recommendations",
 "description": "Vertical Pod Autoscalar Recommendations vs. Utilization vs. Requests & Limits",
 "tags": [
  "Autoscaling",
  "VPA"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_labels, namespace)"
    }
   },
   {
    "name": "targetName",
    "label": "Target",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_labels{namespace=\"$namespace\"}, target_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{namespace=\"$namespace\", target_name=\"$targetName\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "container",
   "targets": [
    {}
   ]
  },
  {
   "title": "$container CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$targetName-(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "$container CPU Guaranteed QoS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{resource=\"cpu\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{resource=\"cpu\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "$container CPU Burstable QoS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{resource=\"cpu\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{resource=\"cpu\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "CPU Limits"
    }
   ]
  },
  {
   "title": "$container Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "$container Memory Guaranteed QoS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{resource=\"memory\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "avg(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{resource=\"memory\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "$container Memory Burstable QoS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{resource=\"memory\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "avg(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{resource=\"memory\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "Memory Limits"
    }
   ]
  },
  {
   "title": "CPU Usage, Requests, Limits vs Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$targetName-(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} actual usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} limits"
    },
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{resource=\"cpu\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} recommendation target"
    },
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{resource=\"cpu\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} recommendation lowerbound"
    },
    {
     "expr": "sum(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{resource=\"cpu\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} recommendation upperbound"
    }
   ]
  },
  {
   "title": "Memory Usage, Requests, Limits vs Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} actual usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=~\"$targetName(.+)\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} limits"
    },
    {
     "expr": "avg(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_target{resource=\"memory\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} recommendation target"
    },
    {
     "expr": "avg(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{resource=\"memory\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} recommendation lowerbound"
    },
    {
     "expr": "avg(kube_customresource_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{resource=\"memory\", namespace=\"$namespace\", target_name=\"$targetName\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} recommendation upperbound"
    }
   ]
  }
 ]
}